Graphic Interface for MM
RVCorp/GamesToGo pull request #3
Opened 2020-02-29 23:16 UTC by Rovehacks

2020-02-29 23:18 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/EmptyScreen.cs
> +                    Height = 30,                    //Con altura de 50 pixeles
why was this modified?

2020-02-29 23:26 UTC, ColdVolcano requested changes

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/EmptyScreen.cs
> +                    Origin = Anchor.TopLeft,
Why was this modified?

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                            proyectCreation = new Container
this has no reason to be a variable

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                    new FillFlowContainer
however, this has to be if we want to modify it later

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                background = new Box
Also no need to save as variable

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Graphics/ProjectDescriptionButton.cs
> +                    Position = new osuTK.Vector2(15,5),
add a using for the osuTK instead of explicitly having it here

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Graphics/ProjectDescriptionButton.cs
> +                TextBackground= new Box
Nitpick, but always leave a space between operators and variables/constants

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Graphics/ProjectDescriptionButton.cs
> +        public SpriteText ProyectName;
Why is this public?

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Graphics/ProjectDescriptionButton.cs
> +        public Box TextBackground;
This isn't even used

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                screenDivition = new GridContainer
Not sure if it needs to be saved

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                            {
If these are going to be like this for all buttons, then apply them at component level

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +        protected override void LoadComplete()
Also a nitpick, leave an empty line between functions.

2020-02-29 23:26 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                        Position= new Vector2(0,125),
One last nitpick, leave a space after a comma

2020-03-01 00:42 UTC, ColdVolcano requested changes

2020-03-01 00:42 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
>          private Box background;
you're not using this anyomore, so delete it.

2020-03-01 00:42 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                        Position = new Vector2(0,125),
why

2020-03-01 00:42 UTC, ColdVolcano commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                        Origin = Anchor.TopCentre,
_cries in extra spaces_

2020-03-01 02:07 UTC, Rovehacks commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                        Position = new Vector2(0,125),
xdxdxd

2020-03-01 02:07 UTC, Rovehacks commented on GamesToGo.Desktop/Screens/MainMenuScreen.cs
> +                                        Origin = Anchor.TopCentre,
xdxdxdxddxdxdxd

2020-03-01 02:15 UTC, ColdVolcano approved these changes
I shall rest in peace

2020-03-01 02:16 UTC, merged